name: CI CD

on: [ push ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'

      - run: npm ci
      - run: npm run build:prod

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Deploy
        uses: fjogeleit/http-request-action@v1.15.4
        with:
          url: ${{ secrets.DEPLOYEER_URL }}
          method: 'POST'
          username: ${{ secrets.DEPLOYEER_USERNAME }}
          password: ${{ secrets.DEPLOYEER_PASSWORD }}
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"project": "studyum", "app": "web-schedule", "async": true}'
